### ISSUE TITLE
Package not available in npm

### ISSUE THREAD

**Issue by erikeckhardt** [godspeedelbow/eslint-plugin-express#1]
This package doesn't seem to be available in npm under `eslint-plugin-express`. Is there a plan to publish it?

**Comment by godspeedelbow** [comment]
I totally forgot I ever wrote this, haha. I will publish it tonight

**Comment by erikeckhardt** [comment]
I was actually looking for something that made eslint recognize express methods and properties like router.get(), but your code looked interesting as I recently had a bug introduced when someone removed the `next` argument just as your readme describes.

**Comment by godspeedelbow** [comment]
Ah ok, well reason I didn't publish this was because it was just an exercise for me in working with ASTs. I ran into the issue you described and figured it would be a good real-world scenario. If you're interested in using it, just use the code. Do whatever you want with it.

I am assuming now that you don't want it on NPM :)

**Comment by erikeckhardt** [comment]
Sure, no need to publish it. Maybe I’ll learn something digging through the source code.

**Comment by godspeedelbow** [comment]
👍👍
